{
    'name': 'BIW-HSBC Banking API Integration',
    'version': '15.0.0.0',
    'license': 'LGPL-3',
    'author': 'PMCPL',
    'category': 'Accounting',
    'website': 'http://int.primeminds.co/',
    'summary': 'Integration of hsbc banking API BIW',
    'sequence': 10,
    'description': """""",
    'depends': ['base', 'account'],
    'data': ['security/ir.model.access.csv',
             'data/integration_data.xml',
             'data/journal_bank.xml',
             'data/sequence.xml',
             'views/acco_payments.xml',
             'views/hsbc_acco_payments.xml',
             'views/hsbc_api_logs.xml'],
    'installable': True,
    'application': False,
    'auto_install': False,
}